# Site settings
title: Matrix Library
email: buaa.zhanghui@gmail.com
description: Tutorial for BLAS, LAPACK, SCALAPACK, including both dense and sparse versions.
lang: en-US
encoding: UTF-8

baseurl: "/docs-matrix-library" # the subpath of your site, e.g. /blog/
url: https://ericzhng.github.io # the base hostname & protocol for your site
git_address: https://github.com/ericzhng/matrix-library
#git_edit_address: https://github.com/UniversalSplitScreen/UniversalSplitScreen.github.io/blob/gh-pages

# theme options from https://bootswatch.com/
# comment out this to use default Bootstrap
bootwatch: paper
#bootwatch: Flatly

# Build settings
markdown: kramdown
highlighter: rouge
plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-sitemap

exclude:
  - Gemfile
  - Gemfile.lock
  - .idea/
  - .gitignore
  - README.md
timezone: America/Detroit
defaults:
- scope:
    path: _posts
    type: posts
  values:
    layout: post
    sectionid: blog

- scope:
    path: _docs
    type: docs
  values:
    layout: docs
    sectionid: docs
    seo:
      type: "WebPage"

collections:
  docs:
    permalink: /:collection/:path/
    output: true
  posts:
    permalink: /blog/:year/:month/:day/:title/
    output: true

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
